image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache bash

stages:
 - test

test-mocha:
  stage: test
  tags:
   - docker
  script:
   - docker run --rm $(docker build -q .) npm test

test-codequality:
  stage: test
  tags:
   - docker
  script:
   - docker run --rm $(docker build -q .) npm run-script pretest
